### ISSUE TITLE
Crash when trying to capture AudioStream on TrackSubscribed

### ISSUE THREAD

**Issue by NaxYo** [livekit/node-sdks#312]
I'm building a simple agent with little to no logic yet. I want to do some processing with the audio tracks, so I'm basing it of [this example](https://docs.livekit.io/agents/build/tracks/).

Every time the agent reaches `new AudioStream(track);`, Node will crash with the following error:

```
Connected to room
thread '<unnamed>' panicked at src/nodejs.rs:52:13:
failed to handle request: invalid request: handle not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7398191717ba - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1b9dad2a88e955ff
   1:     0x739818bafcbb - core::fmt::write::h4b5a1270214bc4a7
   2:     0x7398191453f2 - std::io::Write::write_fmt::hd04af345a50c312d
   3:     0x7398191762b7 - std::panicking::default_hook::{{closure}}::h96ab15e9936be7ed
   4:     0x739819177555 - std::panicking::rust_panic_with_hook::hfe205f6954b2c97b
   5:     0x739819176d22 - std::panicking::begin_panic_handler::{{closure}}::h6cb44b3a50f28c44
   6:     0x739819176cb9 - std::sys::backtrace::__rust_end_short_backtrace::hf1c1f2a92799bb0e
   7:     0x739819176ca4 - rust_begin_unwind
   8:     0x739818af3c84 - core::panicking::panic_nounwind_fmt::h4c4dc67d0bbc166c
   9:     0x739818af3cec - core::panicking::panic_nounwind::hb98133c151c787e4
  10:     0x739818af3c99 - core::panicking::panic_cannot_unwind::he9511e6e72319a3e
  11:     0x7398190d7756 - rtc_node::nodejs::__napi__livekit_ffi_request::hbaa92fe952824907
  12:           0xc51049 - _ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  13:           0xf57eaf - _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  14:           0xf5871d - _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
  15:           0xf58be5 - _ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
  16:          0x1963df6 - Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit
thread caused non-unwinding panic. aborting.
```

The error seems to be related to the Rust binaries, so please, let me know if I should be reporting this issue somewhere else.
I'm currently running on Node `v20.14.0`, Linux Ubuntu 22.04.5; but I have tested in other Node versions, and in Mac, with the same results.

Full agent code:

```ts
import {
  type JobContext,
  WorkerOptions,
  cli,
  defineAgent
} from '@livekit/agents';

import {
  AudioStream,
  RemoteParticipant,
  RemoteTrack,
  RemoteTrackPublication,
  RoomEvent,
  TrackKind
} from '@livekit/rtc-node';

import { fileURLToPath } from 'node:url';

export default defineAgent({
  entry: async (ctx: JobContext) => {
    ctx.room.on(RoomEvent.TrackSubscribed, async (
      track: RemoteTrack,
      publication: RemoteTrackPublication,
      participant: RemoteParticipant
    ) => {
      if (track.kind === TrackKind.KIND_AUDIO) {
        new AudioStream(track);
      }
    });

    await ctx.connect();
    console.log('Connected');
  },
});

cli.runApp(new WorkerOptions({ agent: fileURLToPath(import.meta.url) }));
```

**Comment by NaxYo** [comment]
I can no longer reproduce the issue with the newer version of the package, so I think this one has been fixed. Cheers!
